name: Nova CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    name: Test, Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: 3. Code formatting check
        run: deno fmt --check

      - name: 4. Compile Nova
        run: deno task compile
      # - name: 4. Linting durchführen
      #   run: deno lint

      # - name: 5. Unit- & Integrationstests ausführen
      #   run: deno test -A --doc --coverage=coverage.lcov

      # Optional: Code-Coverage-Report hochladen
      # - name: 6. Coverage an Codecov senden
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # Muss in den Repository-Secrets hinterlegt werden
      #     files: ./coverage.lcov
