name: Nova Release

on:
  push:
    tags: 
      - 'v*.*.*-*' # Release every new tag, which starts with 'v'

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: nova-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: nova-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: nova-macos-arm64

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: 3. Compile application
        run: deno task compile

      - name: 4. Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # Erforderlich, um ein Release zu erstellen
    steps:
      - name: 1. Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 2. Create GitHub Release and attach artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Nova ${{ github.event.inputs.version }}
          body: 'New Nova Version available!'
          files: |
            artifacts/nova-linux-amd64/nova-linux-amd64
            artifacts/nova-macos-amd64/nova-macos-amd64
            artifacts/nova-macos-arm64/nova-macos-arm64

  update-homebrew:
    name: Homebrew Tap actualisation
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v4
        with:
          # Der Name der Formel-Datei in Ihrem Tap (z.B. nova.rb)
          formula-name: nova
          # Ihr Homebrew Tap Repository
          tap-repository: munichbughunter/homebrew-nova
          # Der Tag des neuen GitHub Releases
          tag-name: ${{ github.event.inputs.version }}
          # Ein Personal Access Token (PAT) mit repo-Zugriff auf den Tap
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

  notify-discord:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: update-homebrew
    steps:
      - name: Send Discord Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: '🚀 Nova Release: ${{ github.event.inputs.version }}'
          description: |
            A new version of **Nova** has been successfully released!

            **Installation/Update via Homebrew:**
            ```
            brew upgrade nova
            ```
          color: '3447003' # Blau
          footer: 'Nova Release Pipeline'
